export const homeObjOne={
    lightBg: true,
    imgStart:'start',
    lightTopLine:false,
    lightText:false,
    primary:true,
    buttonlabel:'Get Start',
    lightSub:false,
    sub:'Kami akan Mmebuatkan Anda Kue', 
    headLine:'ayo ayo segera pesan',
    img:require('../../Images/sweet-3.jpg').default,
    alt:'Image',
    start:'true',
}
export const homeObjTwo={
    lightBg: false,
    imgStart:'start',
    lightTopLine:false,
    lightText:false,
    primary:false,
    buttonlabel:'Get Start',
    lightSub:false,
    topLine:'hahahahhah yamiii', 
    sub:'Kami akan Mmebuatkan Anda Kue', 
    headLine:'ayo ayo segera pesan',
    img:require('../../Images/sss.svg').default,
    alt:'Image',
    start:'true',
}
export const homeObjTre={
    lightBg: true,
    imgStart:'',
    lightTopLine:true,
    lightText:true,
    primary:true,
    buttonlabel:'Get Start',
    lightSub:true,
    topLine:'hahahahhah yamiii', 
    sub:'Kami akan Mmebuatkan Anda Kue', 
    headLine:'ayo ayo segera pesan',
    img:require('../../Images/sss.svg').default,
    alt:'Image',
    start:'',
}